import tkinter as tk
from tkinter import *
r=Tk()
T=Text(r,height=2,width=15)
T.grid(row=0,column=1)
T.insert(END,"10 ")
T=Text(r,height=2,width=15)
T.grid(row=1,column=1)
T.insert(END,"20 ")
T=Text(r,height=2,width=15)
T.grid(row=2,column=1)
T.insert(END,"30")
T=Text(r,height=2,width=15)
T.grid(row=0,column=3)
T.insert(END,"40 ")
T=Text(r,height=2,width=15)
T.grid(row=1,column=3)
T.insert(END,"50 ")
T=Text(r,height=2,width=15)
T.grid(row=2,column=3)
T.insert(END,"60")
l1=Label(r,text="burgur",height=2,width=15).grid(row=0,column=0)
l2=Label(r,text="pizza",height=2,width=15).grid(row=1,column=0)
l3=Label(r,text="chineas",height=2,width=15).grid(row=2,column=0)
l4=Label(r,text="rrdy",height=2,width=15).grid(row=0,column=2)
l5=Label(r,text="chfvj",height=2,width=15).grid(row=1,column=2)
l6=Label(r,text="hcjhy",height=2,width=15).grid(row=2,column=2)
button=tk.Button(r,text='add',width=25)
button.grid(row=3,column=0)
button=tk.Button(r,text='reset',width=25)
button.grid(row=3,column=1)
button=tk.Button(r,text='count',width=25)
button.grid(row=3,column=2)
button=tk.Button(r,text='total',width=25)
button.grid(row=3,column=3)
r.mainloop()
